FROM golang:1.18 as builder
RUN apt-get update -qq && apt-get install -y git make
WORKDIR /go/src/github.com/moov-io/iso20022
COPY . .
RUN go mod download && go mod vendor
WORKDIR /go/src/github.com/moov-io/iso20022/test/fuzz-reader
RUN make install
RUN make fuzz-build
ENTRYPOINT make fuzz-run
