// Code generated by xsdgen. DO NOT EDIT.

package camt_v04

type ClearingSystemIdentification2Choice struct {
	Cd    ExternalClearingSystemIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 Cd"`
	Prtry Max35Text                                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 Prtry"`
}

type ClearingSystemMemberIdentification2 struct {
	ClrSysId ClearingSystemIdentification2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 ClrSysId,omitempty"`
	MmbId    Max35Text                           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 MmbId"`
}

type Document struct {
	GetMmb GetMemberV04 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 GetMmb"`
}

// Must be at least 1 items long
type ExternalClearingSystemIdentification1Code string

// Must be at least 1 items long
type ExternalEnquiryRequestType1Code string

// Must be at least 1 items long
type ExternalFinancialInstitutionIdentification1Code string

// Must be at least 1 items long
type ExternalPaymentControlRequestType1Code string

// Must be at least 1 items long
type ExternalSystemMemberType1Code string

type FinancialIdentificationSchemeName1Choice struct {
	Cd    ExternalFinancialInstitutionIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 Cd"`
	Prtry Max35Text                                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 Prtry"`
}

type GenericFinancialIdentification1 struct {
	Id      Max35Text                                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 Id"`
	SchmeNm FinancialIdentificationSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 SchmeNm,omitempty"`
	Issr    Max35Text                                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 Issr,omitempty"`
}

type GenericIdentification1 struct {
	Id      Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 Id"`
	SchmeNm Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 SchmeNm,omitempty"`
	Issr    Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 Issr,omitempty"`
}

type GetMemberV04 struct {
	MsgHdr      MessageHeader9         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 MsgHdr"`
	MmbQryDef   MemberQueryDefinition4 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 MmbQryDef,omitempty"`
	SplmtryData []SupplementaryData1   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 SplmtryData,omitempty"`
}

type MemberCriteria4 struct {
	NewQryNm Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 NewQryNm,omitempty"`
	SchCrit  []MemberSearchCriteria4 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 SchCrit,omitempty"`
	RtrCrit  MemberReturnCriteria1   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 RtrCrit,omitempty"`
}

type MemberCriteriaDefinition2Choice struct {
	QryNm   Max35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 QryNm"`
	NewCrit MemberCriteria4 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 NewCrit"`
}

type MemberIdentification3Choice struct {
	BICFI       BICFIDec2014Identifier              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 BICFI"`
	ClrSysMmbId ClearingSystemMemberIdentification2 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 ClrSysMmbId"`
	Othr        GenericFinancialIdentification1     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 Othr"`
}

type MemberQueryDefinition4 struct {
	QryTp   QueryType2Code                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 QryTp,omitempty"`
	MmbCrit MemberCriteriaDefinition2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 MmbCrit,omitempty"`
}

type MemberReturnCriteria1 struct {
	NmInd        bool `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 NmInd,omitempty"`
	MmbRtrAdrInd bool `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 MmbRtrAdrInd,omitempty"`
	AcctInd      bool `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 AcctInd,omitempty"`
	TpInd        bool `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 TpInd,omitempty"`
	StsInd       bool `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 StsInd,omitempty"`
	CtctRefInd   bool `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 CtctRefInd,omitempty"`
	ComAdrInd    bool `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 ComAdrInd,omitempty"`
}

type MemberSearchCriteria4 struct {
	Id  []MemberIdentification3Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 Id,omitempty"`
	Tp  []SystemMemberType1Choice     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 Tp,omitempty"`
	Sts []SystemMemberStatus1Choice   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 Sts,omitempty"`
}

// May be one of ENBL, DSBL, DLTD, JOIN
type MemberStatus1Code string

type MessageHeader9 struct {
	MsgId   Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 MsgId"`
	CreDtTm ISODateTime        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 CreDtTm,omitempty"`
	ReqTp   RequestType4Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 ReqTp,omitempty"`
}

// May be one of ALLL, CHNG, MODF, DELD
type QueryType2Code string

type RequestType4Choice struct {
	PmtCtrl ExternalPaymentControlRequestType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 PmtCtrl"`
	Enqry   ExternalEnquiryRequestType1Code        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 Enqry"`
	Prtry   GenericIdentification1                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 Prtry"`
}

type SupplementaryData1 struct {
	PlcAndNm Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}

type SystemMemberStatus1Choice struct {
	Cd    MemberStatus1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 Cd"`
	Prtry Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 Prtry"`
}

type SystemMemberType1Choice struct {
	Cd    ExternalSystemMemberType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 Cd"`
	Prtry Max35Text                     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.013.001.04 Prtry"`
}
