// Code generated by xsdgen. DO NOT EDIT.

package camt_v04

import (
	"bytes"
	"encoding/xml"
	"time"
)

// Must match the pattern [A-Z]{3,3}
type ActiveOrHistoricCurrencyCode string

type CurrencyExchange7 struct {
	XchgRate float64                      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 XchgRate"`
	QtdCcy   ActiveOrHistoricCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 QtdCcy"`
	QtnDt    ISODateTime                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 QtnDt"`
}

type CurrencyExchangeReport3 struct {
	CcyRef       CurrencySourceTarget1            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 CcyRef"`
	CcyXchgOrErr ExchangeRateReportOrError2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 CcyXchgOrErr"`
}

type CurrencySourceTarget1 struct {
	SrcCcy  ActiveOrHistoricCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 SrcCcy"`
	TrgtCcy ActiveOrHistoricCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 TrgtCcy"`
}

type Document struct {
	RtrCcyXchgRate ReturnCurrencyExchangeRateV04 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 RtrCcyXchgRate"`
}

type ErrorHandling1Choice struct {
	Cd    ErrorHandling1Code   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 Cd"`
	Prtry Max4AlphaNumericText `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 Prtry"`
}

// May be one of X020, X030, X050
type ErrorHandling1Code string

type ErrorHandling3 struct {
	Err  ErrorHandling1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 Err"`
	Desc Max140Text           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 Desc,omitempty"`
}

type ExchangeRateReportOrError1Choice struct {
	CcyXchgRpt []CurrencyExchangeReport3 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 CcyXchgRpt"`
	OprlErr    []ErrorHandling3          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 OprlErr"`
}

type ExchangeRateReportOrError2Choice struct {
	BizErr  []ErrorHandling3  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 BizErr"`
	CcyXchg CurrencyExchange7 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 CcyXchg"`
}

// Must be at least 1 items long
type ExternalEnquiryRequestType1Code string

// Must be at least 1 items long
type ExternalPaymentControlRequestType1Code string

type GenericIdentification1 struct {
	Id      Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 Id"`
	SchmeNm Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 SchmeNm,omitempty"`
	Issr    Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 Issr,omitempty"`
}

type ISODateTime time.Time

func (t *ISODateTime) UnmarshalText(text []byte) error {
	return (*xsdDateTime)(t).UnmarshalText(text)
}
func (t ISODateTime) MarshalText() ([]byte, error) {
	return xsdDateTime(t).MarshalText()
}

// Must be at least 1 items long
type Max140Text string

// Must be at least 1 items long
type Max350Text string

// Must be at least 1 items long
type Max35Text string

// Must match the pattern [a-zA-Z0-9]{1,4}
type Max4AlphaNumericText string

type MessageHeader7 struct {
	MsgId       Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 MsgId"`
	CreDtTm     ISODateTime            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 CreDtTm,omitempty"`
	ReqTp       RequestType4Choice     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 ReqTp,omitempty"`
	OrgnlBizQry OriginalBusinessQuery1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 OrgnlBizQry,omitempty"`
	QryNm       Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 QryNm,omitempty"`
}

type OriginalBusinessQuery1 struct {
	MsgId   Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 MsgId"`
	MsgNmId Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 MsgNmId,omitempty"`
	CreDtTm ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 CreDtTm,omitempty"`
}

type RequestType4Choice struct {
	PmtCtrl ExternalPaymentControlRequestType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 PmtCtrl"`
	Enqry   ExternalEnquiryRequestType1Code        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 Enqry"`
	Prtry   GenericIdentification1                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 Prtry"`
}

type ReturnCurrencyExchangeRateV04 struct {
	MsgHdr      MessageHeader7                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 MsgHdr"`
	RptOrErr    ExchangeRateReportOrError1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 RptOrErr"`
	SplmtryData []SupplementaryData1             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 SplmtryData,omitempty"`
}

type SupplementaryData1 struct {
	PlcAndNm Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.017.001.04 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}

type xsdDateTime time.Time

func (t *xsdDateTime) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalText() ([]byte, error) {
	return []byte((time.Time)(t).Format("2006-01-02T15:04:05.999999999")), nil
}
func (t xsdDateTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDateTime) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
func _unmarshalTime(text []byte, t *time.Time, format string) (err error) {
	s := string(bytes.TrimSpace(text))
	*t, err = time.Parse(format, s)
	if _, ok := err.(*time.ParseError); ok {
		*t, err = time.Parse(format+"Z07:00", s)
	}
	return err
}
