// Code generated by xsdgen. DO NOT EDIT.

package camt_v04

type CurrencyCriteriaDefinition1Choice struct {
	QryNm   Max35Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.016.001.04 QryNm"`
	NewCrit CurrencyExchangeCriteria2 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.016.001.04 NewCrit"`
}

type CurrencyExchangeCriteria2 struct {
	NewQryNm Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.016.001.04 NewQryNm,omitempty"`
	SchCrit  []CurrencyExchangeSearchCriteria1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.016.001.04 SchCrit"`
}

type CurrencyExchangeSearchCriteria1 struct {
	SrcCcy  ActiveOrHistoricCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:camt.016.001.04 SrcCcy"`
	TrgtCcy ActiveOrHistoricCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:camt.016.001.04 TrgtCcy"`
}

type CurrencyQueryDefinition3 struct {
	QryTp   QueryType2Code                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.016.001.04 QryTp,omitempty"`
	CcyCrit CurrencyCriteriaDefinition1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.016.001.04 CcyCrit,omitempty"`
}

type Document struct {
	GetCcyXchgRate GetCurrencyExchangeRateV04 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.016.001.04 GetCcyXchgRate"`
}

type GetCurrencyExchangeRateV04 struct {
	MsgHdr      MessageHeader1           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.016.001.04 MsgHdr"`
	CcyQryDef   CurrencyQueryDefinition3 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.016.001.04 CcyQryDef,omitempty"`
	SplmtryData []SupplementaryData1     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.016.001.04 SplmtryData,omitempty"`
}

type MessageHeader1 struct {
	MsgId   Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.016.001.04 MsgId"`
	CreDtTm ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:camt.016.001.04 CreDtTm,omitempty"`
}

// May be one of ALLL, CHNG, MODF, DELD
type QueryType2Code string

type SupplementaryData1 struct {
	PlcAndNm Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.016.001.04 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.016.001.04 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}
