// Code generated by xsdgen. DO NOT EDIT.

package reda_v01

type AddressType3Choice struct {
	Cd    AddressType2Code        `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Cd"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Prtry"`
}

type Contact4 struct {
	NmPrfx    NamePrefix2Code             `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 NmPrfx,omitempty"`
	Nm        Max140Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Nm,omitempty"`
	PhneNb    PhoneNumber                 `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 PhneNb,omitempty"`
	MobNb     PhoneNumber                 `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 MobNb,omitempty"`
	FaxNb     PhoneNumber                 `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 FaxNb,omitempty"`
	EmailAdr  Max2048Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 EmailAdr,omitempty"`
	EmailPurp Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 EmailPurp,omitempty"`
	JobTitl   Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 JobTitl,omitempty"`
	Rspnsblty Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Rspnsblty,omitempty"`
	Dept      Max70Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Dept,omitempty"`
	Othr      []OtherContact1             `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Othr,omitempty"`
	PrefrdMtd PreferredContactMethod1Code `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 PrefrdMtd,omitempty"`
}

type CreditorEnrolment3 struct {
	Enrlmnt      CreditorServiceEnrolment1      `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Enrlmnt"`
	CdtrTradgNm  Max140Text                     `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 CdtrTradgNm,omitempty"`
	Cdtr         RTPPartyIdentification1        `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Cdtr"`
	UltmtCdtr    RTPPartyIdentification1        `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 UltmtCdtr,omitempty"`
	MrchntCtgyCd MerchantCategoryCodeIdentifier `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 MrchntCtgyCd"`
	CdtrLogo     Max10KBinary                   `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 CdtrLogo,omitempty"`
}

type CreditorEnrolmentStatusReason2 struct {
	Orgtr    RTPPartyIdentification1              `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Orgtr,omitempty"`
	Rsn      CreditorEnrolmentStatusReason2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Rsn"`
	AddtlInf []Max105Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 AddtlInf,omitempty"`
}

type CreditorEnrolmentStatusReason2Choice struct {
	Cd    ExternalCreditorEnrolmentStatusReason1Code `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Cd"`
	Prtry Max35Text                                  `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Prtry"`
}

type CreditorServiceEnrolment1 struct {
	EnrlmntStartDt  DateAndDateTime2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 EnrlmntStartDt,omitempty"`
	EnrlmntEndDt    DateAndDateTime2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 EnrlmntEndDt,omitempty"`
	Vsblty          Visibilty1             `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Vsblty,omitempty"`
	SvcActvtnAllwd  bool                   `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 SvcActvtnAllwd"`
	SvcDescLk       Max2048Text            `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 SvcDescLk,omitempty"`
	CdtrSvcActvtnLk Max2048Text            `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 CdtrSvcActvtnLk,omitempty"`
}

type DateAndDateTime2Choice struct {
	Dt   ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Dt"`
	DtTm ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 DtTm"`
}

type DateAndPlaceOfBirth1 struct {
	BirthDt     ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 BirthDt"`
	PrvcOfBirth Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 PrvcOfBirth,omitempty"`
	CityOfBirth Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 CityOfBirth"`
	CtryOfBirth CountryCode `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 CtryOfBirth"`
}

type Document struct {
	ReqToPayCdtrEnrlmntStsRpt RequestToPayCreditorEnrolmentStatusReportV01 `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 ReqToPayCdtrEnrlmntStsRpt"`
}

type EnrolmentHeader2 struct {
	MsgId    Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 MsgId"`
	CreDtTm  ISODateTime             `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 CreDtTm"`
	MsgOrgtr RTPPartyIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 MsgOrgtr,omitempty"`
	MsgRcpt  RTPPartyIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 MsgRcpt,omitempty"`
	InitgPty RTPPartyIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 InitgPty"`
}

type EnrolmentStatus2 struct {
	OrgnlBizInstr   OriginalBusinessInstruction1   `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 OrgnlBizInstr,omitempty"`
	Sts             ServiceStatus1Choice           `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Sts"`
	StsRsn          CreditorEnrolmentStatusReason2 `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 StsRsn,omitempty"`
	OrgnlEnrlmntRef OriginalEnrolment2Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 OrgnlEnrlmntRef,omitempty"`
	FctvEnrlmntDt   DateAndDateTime2Choice         `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 FctvEnrlmntDt,omitempty"`
	SplmtryData     []SupplementaryData1           `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 SplmtryData,omitempty"`
}

// Must match the pattern [a-zA-Z0-9]{4}
type Exact4AlphaNumericText string

// Must be at least 1 items long
type ExternalCreditorEnrolmentStatusReason1Code string

// Must be at least 1 items long
type ExternalOrganisationIdentification1Code string

// Must be at least 1 items long
type ExternalPersonIdentification1Code string

type GenericIdentification30 struct {
	Id      Exact4AlphaNumericText `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Id"`
	Issr    Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Issr"`
	SchmeNm Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 SchmeNm,omitempty"`
}

type GenericOrganisationIdentification1 struct {
	Id      Max35Text                                   `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Id"`
	SchmeNm OrganisationIdentificationSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 SchmeNm,omitempty"`
	Issr    Max35Text                                   `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Issr,omitempty"`
}

type GenericPersonIdentification1 struct {
	Id      Max35Text                             `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Id"`
	SchmeNm PersonIdentificationSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 SchmeNm,omitempty"`
	Issr    Max35Text                             `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Issr,omitempty"`
}

type OrganisationIdentification37 struct {
	AnyBIC   AnyBICDec2014Identifier              `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 AnyBIC,omitempty"`
	LEI      LEIIdentifier                        `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 LEI,omitempty"`
	EmailAdr Max256Text                           `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 EmailAdr,omitempty"`
	Othr     []GenericOrganisationIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Othr,omitempty"`
}

type OrganisationIdentificationSchemeName1Choice struct {
	Cd    ExternalOrganisationIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Cd"`
	Prtry Max35Text                               `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Prtry"`
}

type OriginalBusinessInstruction1 struct {
	MsgId   Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 MsgId"`
	MsgNmId Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 MsgNmId,omitempty"`
	CreDtTm ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 CreDtTm,omitempty"`
}

type OriginalEnrolment2Choice struct {
	OrgnlCdtrId      Party49Choice      `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 OrgnlCdtrId"`
	OrgnlEnrlmntData CreditorEnrolment3 `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 OrgnlEnrlmntData"`
}

type OtherContact1 struct {
	ChanlTp Max4Text   `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 ChanlTp"`
	Id      Max128Text `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Id,omitempty"`
}

type Party49Choice struct {
	OrgId  OrganisationIdentification37 `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 OrgId"`
	PrvtId PersonIdentification17       `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 PrvtId"`
}

type PersonIdentification17 struct {
	DtAndPlcOfBirth DateAndPlaceOfBirth1           `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 DtAndPlcOfBirth,omitempty"`
	EmailAdr        Max256Text                     `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 EmailAdr,omitempty"`
	Othr            []GenericPersonIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Othr,omitempty"`
}

type PersonIdentificationSchemeName1Choice struct {
	Cd    ExternalPersonIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Cd"`
	Prtry Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Prtry"`
}

type PostalAddress24 struct {
	AdrTp       AddressType3Choice `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 AdrTp,omitempty"`
	Dept        Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Dept,omitempty"`
	SubDept     Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 SubDept,omitempty"`
	StrtNm      Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 StrtNm,omitempty"`
	BldgNb      Max16Text          `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 BldgNb,omitempty"`
	BldgNm      Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 BldgNm,omitempty"`
	Flr         Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Flr,omitempty"`
	PstBx       Max16Text          `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 PstBx,omitempty"`
	Room        Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Room,omitempty"`
	PstCd       Max16Text          `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 PstCd,omitempty"`
	TwnNm       Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 TwnNm,omitempty"`
	TwnLctnNm   Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 TwnLctnNm,omitempty"`
	DstrctNm    Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 DstrctNm,omitempty"`
	CtrySubDvsn Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 CtrySubDvsn,omitempty"`
	Ctry        CountryCode        `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Ctry,omitempty"`
	AdrLine     []Max70Text        `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 AdrLine,omitempty"`
}

// May be one of LETT, MAIL, PHON, FAXX, CELL
type PreferredContactMethod1Code string

type RTPPartyIdentification1 struct {
	Nm        Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Nm,omitempty"`
	PstlAdr   PostalAddress24 `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 PstlAdr,omitempty"`
	Id        Party49Choice   `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Id,omitempty"`
	CtryOfRes CountryCode     `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 CtryOfRes,omitempty"`
	CtctDtls  Contact4        `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 CtctDtls,omitempty"`
}

type RequestToPayCreditorEnrolmentStatusReportV01 struct {
	Hdr                EnrolmentHeader2     `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Hdr"`
	OrgnlEnrlmntAndSts []EnrolmentStatus2   `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 OrgnlEnrlmntAndSts"`
	SplmtryData        []SupplementaryData1 `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 SplmtryData,omitempty"`
}

// May be one of ACPT, RJCT
type ServiceRequestStatus1Code string

type ServiceStatus1Choice struct {
	Cd    ServiceRequestStatus1Code `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Cd"`
	Prtry Max35Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Prtry"`
}

type SupplementaryData1 struct {
	PlcAndNm Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}

type Visibilty1 struct {
	StartDt   DateAndDateTime2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 StartDt,omitempty"`
	EndDt     DateAndDateTime2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 EndDt,omitempty"`
	LtdVsblty bool                   `xml:"urn:iso:std:iso:20022:tech:xsd:reda.069.001.01 LtdVsblty,omitempty"`
}
